version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3502:3502'
    restart: always
    depends_on:
      - server
  client-admin:
    build:
      context: ./client-admin
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3501:3501'
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - database
  database:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'