version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '83:3000'
    restart: always
    env_file: ./client/.env.local
    depends_on:
      - server
    networks:
      - custom


  client-admin:
    build:
      context: ./client-admin
      dockerfile: Dockerfile.prod
    restart: always
    env_file: ./client-admin/.env.local
    ports:
      - '8003:3000'
    depends_on:
      - server
    networks:
      - custom


  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: always
    env_file: ./server/.env.local
    volumes:
      - ./server:/app
    ports:
      - '3003:8000'
    depends_on:
      - db
    networks:
      - custom


  db:
    image: mysql:8
    container_name: movie_mysql
    restart: always
    environment:
      MYSQL_DATABASE: movie_review
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_PASSWORD: "123"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./docker/mysql:/etc/mysql/my.cnf
      - ./mysql_data:/var/lib/mysql
    networks:
      - custom


networks:
  custom: