version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '83:3000'
    restart: always
    depends_on:
      - server
    networks:
      - custom


  client-admin:
    build:
      context: ./client-admin
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '8003:3000'
    depends_on:
      - server
    networks:
      - custom


  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '3003:8000'
    depends_on:
      - database
    networks:
      - custom


  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE='movie_review'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='some_password'
      - MYSQL_ROOT_PASSWORD='some_password'
      - MYSQL_HOST='localhost'
    networks:
      - custom


networks:
  custom: