# Generated by Django 4.2.1 on 2023-05-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seo_title',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
