import './globals.css'
import RootLayoutHeader from './components/Header'
import Transition from './components/Transition'
import { Suspense } from 'react'


export const metadata = {
  title: 'Movie review',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-700'>
        <div className="h-[100vh] flex flex-col overflow-hidden">
            <RootLayoutHeader />
            <div className='flex flex-1 w-full overflow-hidden'>
                {children}
            </div>
        </div>
      </body>
    </html>
  )
}
