import Transition from '@/app/components/Transition'
import { customFetch } from '@/utils/helpers'
import YoutubeData from './components/YoutubeData'


// export const metadata = {
//   title: 'Movie details',
//   description: 'Generated by create next app',
// }


export async function generateMetadata({ params } : {params:{slug: string[]}}) {
    const id = params.slug[0]
    const data = await getReview(id)

    return {
        title: data.title,
        description: data.title, // TODO: add a desc field for reviews
    }
}


const getReview = async (id:string)=>{
    const [res, data] = await customFetch('review/'+id, 'GET')
    return data.item
}


export default async function Review({
    params
}: {
    params:{
        slug: string[]
    }
}) {

    const id = params.slug[0]
    const data = await getReview(id)
    return (
        <Transition>
            <div className="overflow-hidden flex flex-col lg:flex-row p-4 h-full">
                <div className="w-full lg:w-1/2 p-2">
                    <iframe 
                        className="rounded-1 w-full h-90 md:min-h-[400px] shadow-2xl" 
                        src={`https://www.youtube.com/embed/${data?.video}`} 
                        title="YouTube video player" 
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen">
                    </iframe>
                    <YoutubeData videoId={data?.video} />
                </div>
                <div className="w-full lg:w-1/2 p-4 text-white text-lg overflow-auto">
                    <p className='text-3xl text-gray-300'> {data.title}  </p>
                    <p className='text-sm text-gray-300'> {data.tags}  </p>
                    { data?.text && <div dangerouslySetInnerHTML={{ __html: data.text }}></div> }
                </div>
            </div>
        </Transition>
    )
}
